# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

prodint_cpp <- function(A, s, t, n) {
    .Call(`_lifepack_prodint_cpp`, A, s, t, n)
}

